export enum GenderEnum {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
    ANDROGYNE = 'ANDROGYNE',
    BIGENDER = 'BIGENDER',
    AGENDER = 'AGENDER',
    DEMIGENDER = 'DEMIGENDER',
    GENDERFLIID = 'GENDERFLIID',
    TRANSGENDER = 'TRANSGENDER',
    THIRDGENDER = 'THIRDGENDER',
    NONE = 'NONE',
    OTHER = 'OTHER',
}
